language: generic
sudo: required
services:
   - docker

before_install:
   - docker build -t melaminb/docker-react -f Dockerfile.dev .

script:
   - docker run -e CI=true melaminb/docker-react npm run test -- --coverage